name = input  ( "Enter your name?: ")
print  ( "name" )
age = input ("Enter your age")
print("age")
color = input ("Enter your favorite color")
print ("color")
print (f"Hello {name},you are {age}, and your favorite color is {color}")